cement/ext/ext_colorlog.py
AttributeError: 'ColorLogHandler' object has no attribute 'critical'
=> Fix docstring

doc/source/dev/quickstart.rst
=> [FIX] Fix braces in example

doc/source/dev/extending_cementapp.rst
This PR aims to address #340 
It fixes the typo and contains the proposed name change to the api object.
=> Fix typo "Extending CementApp Doc

CONTRIBUTORS, cement/core/handler.py
Fix for registering same handler multiple times
fixes #353 
According documentation:
> Register a handler object to a handler.  If the same object is already
registered then no exception is raised, however if a different object
attempts to be registered to the same name a ``FrameworkError`` is
raised.
But it fails. Example code:
```python
from cement.core.interface import Interface
from cement.core.handler import CementBaseHandler
from cement.core.foundation import CementApp
class MyInterface(Interface):
class IMeta:
label = 'myinterface'
class MyHandler(CementBaseHandler):
class Meta:
interface = MyInterface
label = 'myhandler'
with CementApp('myapp') as app:
app.handler.define(MyInterface)
app.handler.register(MyHandler)
app.handler.register(MyHandler)
```
To fix it `obj` should be …
=> Fix for registering same handler multiple times

cement/core/controller.py
fixes #356 
Replacing deprecated `handler.list()` with `self.app.handler.list()` in [cement.core.controller#L368](https://github.com/datafolklabs/cement/blob/master/cement/core/controller.py#L368)
=> Replacing deprecated handler.list()

cement/core/handler.py
Deprecation message in list() reported about get()
fixes #354
=> Fix in deprecation message in handler.list()

cement/core/controller.py
This allows for use of the Python builtin documentation string for your exposed methods:
```python
class MyController(CementBaseController):
class Meta:
label = 'my_controller'
@expose()
def list(self):
"""
My great method.
This methods does this and that ...
"""
```
=> controller: Add support for function doc in expose

cement/ext/ext_argcomplete.py, doc/source/dev/application_design.rst, doc/source/dev/boss_templates.rst, doc/source/dev/testing.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs links for their .org -> .io migration for hosted projects

cement/ext/ext_jinja2.py, tests/ext/jinja2_tests.py, tests/templates/test_template.jinja2, tests/templates/test_template_utf8.jinja2
Was there a reason jinja2 was not supported as an output handler ?
=> added jinja2 output handler

doc/source/dev/interfaces_and_handlers.rst
Resolves issue #392 
Fixed a simple typo of the word 'Handler' (was 'Hander') inside of the 'interfaces_and_handler' documentation.
=> Fix typo 'Hander' in interfaces_and_handler docs

cement/ext/ext_daemon.py
pwd.getpwuid(os.getuid()) is used instead of os.getlogin() due to errors, see #401
=> Fix getting os user for daemon extension #401

cement/core/foundation.py
Removing all extended members from app during close()
=> Fix for #415. app.extend and reusing app

doc/source/projects_built_on_cement.rst
Add the QLDS Manager for Quake Live Server administrators to the list of
projects built with Cement. Closes #472.
=> Add QLDS Manager to Projects Built on Cement

doc/source/dev/quickstart.rst
This PR addresses issue #443 fixing the [Quick Start](http://cement.readthedocs.io/en/latest/dev/quickstart/) example being cross platform compatible, by removing `daemon` from `extensions` in the example code under the [Getting Warmer](http://cement.readthedocs.io/en/latest/dev/quickstart/#getting-warmer) section.
=> Made changes to 'Doc - Quick Start' for crossplatform compatibility.

cement/core/foundation.py
If changing Meta: config_section of a CementApp it fails to run() with raising `ConfigParser.NoSectionError: No section: '..'`. 
This seems to fix that, through probably it would make sense to use the base_dict above, but I did not want to touch code I barely know :)
=> extensions load to honor config_section

cement/cli/templates/generate/project/{{ label }}/main.py
=> Fix wrong property name: exit_on_close

CHANGELOG.md, CONTRIBUTORS.md, cement/ext/ext_colorlog.py
By having the Meta.label be dynamically fetched when "colorize" is set, one can subclass ColorLogHandler to add further functionality (ie. mailing when a fatal error occurs). 
Now a subclass Handler can be defined, its own class Meta sets the config_defaults and the original ColorLogHandler receives the config from it.
---
**Issue:** #571
=> Change the way ext_colorlog.py locates its config

cement/cli/templates/generate/project/README.md, cement/cli/templates/generate/todo-tutorial/README.md
**Issue:** #588 
Use `python setup.py install` instead of `pip install setup.py` in the templates.
=> Update pip setup.py command in templates (fixes #588)

cement/core/foundation.py, cement/core/handler.py, cement/ext/ext_configparser.py, cement/ext/ext_memcached.py, cement/ext/ext_plugin.py
=> fix deprecated imp usage (#386)

CONTRIBUTORS.md, cement/utils/fs.py
**Issue**: #611
```diff
import os
import tempfile
import shutil
+from datetime import datetime
class Tmp(object):
@@ -170,7 +171,7 @@ def ensure_parent_dir_exists(path):
return ensure_dir_exists(parent_dir)
-def backup(path, suffix='.bak'):
+def backup(path, suffix='.bak', *, add_timestamp=False):
"""
Rename a file or directory safely without overwriting an existing
backup of the same name.
@@ -178,6 +179,7 @@ def backup(path, suffix='.bak'):
Args:
path (str): The path to the file or directory to make a backup of.
suffix (str): The suffix to rename files with.
+        add_timestamp(bool): whether to add a timestamp to the backup suffix
Returns:
str: The new path of backed up file/directory
@@ -194,7 +196,13 @@ def backup(path, suffix='.bak'):
count = -1
new_path = None
path = …
```
=> Issue #611: added option to add timestamp to backups

cement/ext/ext_plugin.py, cement/ext/ext_yaml.py, cement/ext/ext_yaml_configobj.py
- PR is associated with at least one issue: https://github.com/datafolklabs/cement/issues/672
- Submit from a **topic** branch, not a pre-existing Cement branch: Fix210xBranchForPython312
- All tests pass successfully: Yes. I did not add any new tests since the existing tests suffice.
- Coverage reports 100% code coverage: Since I've added a conditional check for Python version < 3.4 in ext_plugin.py coverage of this file has fallen to 93%. I'm open to suggestions.
---
**Issue:** #672
[Guidelines for Code Contributions]: https://github.com/datafolklabs/cement/blob/master/.github/CONTRIBUTING.md#guidelines …
=> Fix 2.10.x branch for Python 3.12 and beyond

cement/ext/ext_smtp.py
1. Respect empty CC and BCC and do not deliver <> to SMTP Server
2. Allow TLS also on non-SSL sessions
3. Turn on debugging before TLS to see that log as well
4. Check for parameter `files` and empty if missed
5. Loop through files and append to attachments
6. Allow Attachment Disposition Name differ from Filename by path/filename.ext=attname.ext
7. Allow body to send in text and html by list or dict
---
**Covered Issues:** 
1. #667 
1. #668
=> Extend ext_smtp.py
