- cement/core/hook.py
- tests/core/hook_tests.py
Enable the use of generator based hooks in cement as per issue #296
> Enable generator based hooks as per issue #296

- cement/core/handler.py
> typo s/param hander_def:/param handler_def:/

- cement/core/output.py
- cement/ext/ext_jinja2.py
- doc/source/dev/output.rst
- tests/ext/jinja2_tests.py
- tests/templates/test_template_child.jinja2
- tests/templates/test_template_parent.jinja2
- tests/templates/test_template_utf8.jinja2
> allow jinja2 template inheritance Fixes #381

- doc/source/dev/quickstart.rst
> docs(quickstart): fix typo

- cement/utils/test.py
> Fix removal of temporary files on Windows on the TestCase tearDown

- doc/source/dev/configuration.rst
- doc/source/dev/interfaces_and_handlers.rst
> Add reference to `super()` in Handler subclass methods

- cement/core/foundation.py
* Adds config_dirs meta variable for application
> Second attempt to solve #414

- LICENSE
- doc/source/conf.py
If I understood the issue correctly this fixes  #451. Let me know if I misunderstood/missed anything.
> Update LICENSE to include 2017 (Resolves issue #451)

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTORS
> Generated GitHub templates

- cement/ext/ext_argparse.py
> Modify ArgparseController to allow multi-line version output.

- CONTRIBUTORS
- cement/core/config.py
- cement/core/handler.py
- cement/ext/ext_configobj.py
- cement/ext/ext_configparser.py
- tests/core/config_tests.py
- tests/ext/configobj_tests.py
- tests/ext/configparser_tests.py
Hey guys, cement is great and I'd like to help.  Let me know if this is what you're looking for on #465 .
> Resolves issue #465. Add ConfigHandler.get_dict.

- .gitignore
**Issue:** #500 
Added .vscode/ to .gitignore
> Add .vscode folder

- tests/cli/test_main.py
- tests/core/test_extension.py
- tests/core/test_foundation.py
**Issue:** #494 
I've added a couple of assertions to tests that had no explicit assertion in them.
Let me know if this is the sort of thing you're looking for, and I'll keep plugging away at the rest of the tests.
> Partially resolves issue #494

- CONTRIBUTORS.md
- cement/cli/templates/generate/project/{{ label }}/core/exc.py
- cement/cli/templates/generate/project/{{ label }}/main.py
---
This is a fix for **Issue:** #535 I opened. I hope it may help 🤞
> Resolve Issue #535

- README.md
- lgtm.yml
Hi there!
I thought you might be interested in adding these LGTM [code quality badges](https://lgtm.com/projects/g/datafolklabs/cement/ci/#badges) to your project. They indicate how you care about code quality and encourage your future contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/datafolklabs/cement).
N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.
> Add LGTM code quality badges

- CONTRIBUTORS.md
- cement/ext/ext_generate.py
- cement/ext/ext_yaml.py
> Resolve Issue #553

- requirements-dev-windows.txt
- requirements-dev.txt
- requirements-rtd.txt
> Resolve Issue #555

- cement/ext/ext_configparser.py
- tests/ext/test_ext_configparser.py
---
**Issue:** #
This PR fixes #558
> Pass kwargs to configparser for getboolean support (#558)

- CONTRIBUTORS.md
- cement/ext/ext_argparse.py
> Fixes #544

- MANIFEST.in
> Fix inclusion of license in pip package

- Dockerfile
- cement/cli/templates/generate/project/Dockerfile
- cement/cli/templates/generate/todo-tutorial/Dockerfile
- docker/Dockerfile.dev
- docker/Dockerfile.dev-py35
- docker/Dockerfile.dev-py36
- docker/Dockerfile.dev-py37
- docker/Dockerfile.dev-py38
According to https://docs.docker.com/engine/reference/builder/#maintainer-deprecated `MAINTAINER` is deprecated.
> Remove MAINTAINER from Dockerfile

- tests/utils/test_fs.py
---
**Issue:** Fixes #662. Additionally a cleanup effort.
All changes are the result of
```bash
pyupgrade --py38-plus cement/**/*.py
pyupgrade --py38-plus tests/**/*.py
```
> pyupgrade --py38-plus

- .travis.yml
- Makefile
- docker-compose.yml
- docker/Dockerfile.dev-py313
- scripts/travis.sh
> add 3.13 image and CI

- .travis.yml
> re-enable 3.13 job

- README.md
- cement/core/extension.py
- cement/core/foundation.py
- cement/ext/ext_argparse.py
- cement/ext/ext_generate.py
- cement/ext/ext_logging.py
- cement/ext/ext_memcached.py
- cement/ext/ext_smtp.py
- cement/utils/version.py
My edits in this PR were solely for README.md and comments in files. No changes to actual code were made.
I had noticed that in some places "it's" was being used where "its" would have been more comprehensible and some places where "its" was being used where "it's" seemed like the better option.
I also removed some commas in a few places to allow what I considered to be better sentence flow and structure
> Made a few punctuation improvements and cleaned up some usage of "its" and "it's"
